<?php

// device fullname for mokee download web site
$device_fullname = array(
    'aries' => 'XiaoMi 2S',
    'crespo' => 'Google Nexus S',
    'd800' => 'LG G2 (AT&T)',
    'd801' => 'LG G2 (T-Mobile)',
    'd802' => 'LG G2 (Intl)',
    'dlx' => 'HTC Droid DNA',
    'e975' => 'LG Optimus G (Intl)',
    'edison' => 'Motorola Atrix 2',
    'find5' => 'Oppo Find 5',
    'galaxysmtd' => 'Samsung Galaxy S',
    'hammerhead' => 'Google Nexus 5',
    'i9100' => 'Samsung Galaxy S II (Intl)',
    'i9100g' => 'Samsung Galaxy S II (G)',
    'i9300' => 'Samsung Galaxy S III (Intl)',
    'i9305' => 'Samsung Galaxy S III (GSM LTE)',
    'jfltexx' => 'Samsung Galaxy S4 (Intl)',
    'jordanplus' => 'Motorola Defy / Defy Plus',
    'm7att' => 'HTC One (AT&T)',
    'm7spr' => 'HTC One (Sprint)',
    'm7tmo' => 'HTC One (T-Mobile)',
    'm7ul' => 'HTC One (GSM)',
    'm7vzw' => 'HTC One (Verizon)',
    'maguro' => 'Google Galaxy Nexus (GSM)',
    'mako' => 'Google Nexus 4',
    'mb886' => 'Motorola Atrix HD ',
    'n7000' => 'Samsung Galaxy Note (Intl)',
    'n7100' => 'Samsung Galaxy Note II (GSM Non-LTE)',
    'p880' => 'LG Optimus 4X HD',
    'p930' => 'LG Nitro HD / Optimus LTE',
    'sc03e' => 'Samsung Galaxy S III (Japan)',
    'spyder' => 'Motorola Droid Razr',
    'umts_spyder' => 'Motorola Razr',
    'xt907' => 'Motorola Droid RAZR M',
    'xt925' => 'Motorola Droid RAZR HD (GSM)',
    'xt926' => 'Motorola Droid RAZR HD (CDMA)',
    'xt1053' => 'Motorola Moto X (T-Mobile)',
    'xt1058' => 'Motorola Moto X (GSM)',
    'xt1060' => 'Motorola Moto X (Verizon)',
    'yuga' => 'Sony Xperia Z',
);
